default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: crowd_development
  username: crowd
  password: <%= ENV['CROWD_DATABASE_PASSWORD'] %>
  host: localhost

test:
  <<: *default
  database: crowd_test
  username: crowd
  password: <%= ENV['CROWD_DATABASE_PASSWORD'] %>
  host: localhost

production:
  <<: *default
  database: crowd_production
  username: crowd
  password: <%= ENV['CROWD_DATABASE_PASSWORD'] %>
  host: localhost
