# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1eb5d21ece566723b0426023d9a78a879d23e04ca8856cfb6023c214c51189a0409a584fbc939444c94a0187442d3bb7d8e1172281d62d197afa994b37d0050

test:
  secret_key_base: 4f4c23aa44164865102e4fb90869e431edb7bf230588b735ea89b0b164f20458f5399b8f37a8c4c3ca840b7b3f45a033d44fa4a09e78703da1458d14d6f10759

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
